### ISSUE TITLE
Delete does not work

### ISSUE THREAD

**Issue by matthewjsummers** [J-Siu/ng2-simple-mq#2]
Hi

Deleting a queue always returns false. This is because of a bug in delQueue:

```
delQueue(name: string): boolean {
		if (name === undefined || !this.mq['name']) {
			return false;
		}
		let s = this.getSubscription();
		// unsubscribe all subscription for queue 'name'
		s.forEach(i => {
			if (this.subscription[i].name === name) {
				this.unsubscribe(i);
			}
		});
		// delete queue 'name' subject and observable
		delete this.mq[name].observable;
		delete this.mq[name].subject;
		delete this.mq[name];
	}
```

The first line checks to see if the queue exists:

`if (name === undefined || !this.mq['name']) {`

The "name" parameter should not be in quotes, it should be:

`if (name === undefined || !this.mq[name]) {`

**Comment by J-Siu** [comment]
Thank you!! Fixing now!!

commit 7572719ffede43d7b0949eb9de48ef5b153f21c2 close #2
